{{- if and .Values.pyannote.enabled (or .Values.pyannote.hfToken .Values.pyannote.serviceToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justai.fullname" . }}-pyannote-secrets
  labels:
    {{- include "justai.labels" . | nindent 4 }}
type: Opaque
data:
  hf-token: {{ .Values.pyannote.hfToken | default "" | b64enc | quote }}
  service-token: {{ .Values.pyannote.serviceToken | default "" | b64enc | quote }}
{{- end }}
