{{- if and .Values.secrets.create .Values.secrets.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "justai.fullname" . }}-vs-secrets
  labels:
    {{- include "justai.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.secrets.vault.authRef }}
  type: {{ .Values.secrets.vault.type }}
  mount: {{ .Values.secrets.vault.mount }}
  {{- if .Values.secrets.vault.namespace }}
  namespace: {{ .Values.secrets.vault.namespace }}
  {{- end }}
  path: {{ .Values.secrets.vault.path }}
  refreshAfter: {{ .Values.secrets.vault.refreshAfter }}
  destination:
    create: {{ .Values.secrets.vault.destination.create }}
    name: {{ printf "%s-secrets" (include "justai.fullname" .) }}
{{- end }}
